---
apiVersion: v1
kind: ConfigMap
metadata:
  name: emojify-web-configmap
data:
  config: |
    window.env = {};
    window.env.config = {
      AUTH_URL: 'https://demo.hashicorp.fun/auth',
      API_URL: 'https://demo.hashicorp.fun/api/',
      HOME_URL: 'https://demo.hashicorp.fun/',
      PAYMENT_URL: 'https://demo.hashicorp.fun/api/payments',
      PAYMENT_ENABLED: true,
      OAUTH_ENABLED: false,
      AUTH_DISABLED: true
    };

---
apiVersion: v1
kind: Service
metadata:
  name: emojify-website
  labels:
    app: emojify-website
spec:
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
    name: http
  selector:
    app: emojify-website

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: emojify-website
  labels:
    app: emojify-website
spec:
  replicas: 2
  selector:
    matchLabels:
      app: emojify-website
  template:
    metadata:
      labels:
        app: emojify-website
    spec:
      volumes:
      - name: config
        configMap:
          name: emojify-web-configmap
          items:
          - key: config
            path: env.js
      containers:
      - name: emojify-website
        image: "nicholasjackson/emojify-website:0.5.8"
        imagePullPolicy: Always
        command: ["serve"]
        args: ["-s", "build"]
        ports:
        - containerPort: 5000

        volumeMounts:
        - name: config
          mountPath: /app/build/config/
          readOnly: true
