---
apiVersion: v1
kind: Service
metadata:
 name: ingress-consul
 annotations:
   getambassador.io/config: |
     ---
     apiVersion: ambassador/v1
     kind: Mapping
     name: consul_ingress_mapping
     prefix: /
     service: emojify-website
     resolver: consul-dc1
     load_balancer: 
       policy: round_robin
spec:
 ports:
 - name: https
   port: 443
   targetPort: 8443
