---
apiVersion: getambassador.io/v1
kind: Mapping
metadata:
  name: consul-website-mapping
  namespace: default
spec:
  prefix: /
  host: emojify.today
  service: emojify-website-proxy
  resolver: consul-dc1
  tls: ambassador-consul
  load_balancer:
    policy: round_robin

---
apiVersion: getambassador.io/v1
kind: Mapping
metadata:
  name: consul-api-mapping
  namespace: default
spec:
  prefix: /api/
  timeout_ms: 20000
  host: emojify.today
  service: emojify-api-proxy
  resolver: consul-dc1
  tls: ambassador-consul
  load_balancer:
    policy: round_robin

---
apiVersion: getambassador.io/v1
kind: Mapping
metadata:
  name: consul-grafana-mapping
  namespace: default
spec:
  prefix: /
  host: grafana.emojify.today
  service: grafana-proxy
  resolver: consul-dc1
  tls: ambassador-consul
  load_balancer:
    policy: round_robin
