---
apiVersion: v1
kind: Service
metadata:
  name: emojify-ingress-service
spec:
  selector:
    app: emojify-ingress
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: emojify-ingress-configmap
data:
  config: |
    events {
      worker_connections  1024;
    }

    http {
      upstream emojify-website {
        server 127.0.0.1:8000;
      }
      upstream emojify-api {
        server 127.0.0.1:8001;
      }

      server {
        location / {
          proxy_pass http://emojify-website;
          proxy_set_header Host $host;
        }

        location ~ ^/api(/.*)?$ {
          proxy_pass http://emojify-api$1$is_args$args;
          proxy_pass_request_headers on;
        }
      }
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: emojify-ingress
  labels:
    app: emojify-ingress
spec:
  replicas: 2
  selector:
    matchLabels:
      app: emojify-ingress
  template:
    metadata:
      name: emojify-ingress
      labels:
        app: emojify-ingress
      annotations:
        "consul.hashicorp.com/service-name": "emojify-ingress"
        "consul.hashicorp.com/connect-inject": "true"
        "consul.hashicorp.com/connect-service-upstreams": "emojify-website:8000,emojify-api:8001"
        "consul.hashicorp.com/connect-service-port": "80"
    spec:
      volumes:
      - name: config
        configMap:
          name: emojify-ingress-configmap
          items:
          - key: config
            path: nginx.conf
      containers:
      - name: nginx
        image: nginx:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config
          mountPath: /etc/nginx/

