---
apiVersion: v1
kind: ConfigMap
metadata:
  name: emojify-web-configmap
data:
  config: |
    window.env = {};
    window.env.config = {
      AUTH_URL: '/auth',
      API_URL: '/api/',
      HOME_URL: '/',
      PAYMENT_URL: '/api/payments',
      PAYMENT_ENABLED: false,
      OAUTH_ENABLED: false,
      AUTH_DISABLED: true
    };

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: emojify-website
  labels:
    app: emojify-website
spec:
  replicas: 2
  selector:
    matchLabels:
      app: emojify-website
  template:
    metadata:
      annotations:
        "consul.hashicorp.com/service-name": "emojify-website"
        "consul.hashicorp.com/connect-service-port": "5000"
        "consul.hashicorp.com/connect-inject": "true"
      labels:
        app: emojify-website
    spec:
      volumes:
      - name: config
        configMap:
          name: emojify-web-configmap
          items:
          - key: config
            path: env.js
      containers:
      - name: emojify-website
        image: "nicholasjackson/emojify-website:v0.5.9"
        imagePullPolicy: Always
        command: ["serve"]
        args: ["-s", "build"]
        ports:
        - containerPort: 5000

        volumeMounts:
        - name: config
          mountPath: /app/build/config/
          readOnly: true
